modules_right = []

[general]
	disable_mod = false
	auto_start = true
	space_modules = false
	shadow_text = true
	animations = true
	animationSpeed = 1.0
	fontScale = 1.0
	background_color = 1867534416
	hide_debug_crosshair = true
	hide_sidebar = false
	hide_bossbar = false
	always_show_profiler = false
	always_show_tps = false

[[modules_left]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	enabled = true

	[modules_left.lines]
		minecraft = true

[[modules_left]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "coords"
	name_color = 16733525
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = false
		chunk_relative_coords = false
		chunk_coords = false

[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		dimension = false
		facing = false
		rotation = false
		light = true
		light_server = false
		highest_block = false
		highest_block_server = false
		biome = true
		local_difficulty = true
		day_ticks = false
		days_played = true
		slime_chunk = false

[[modules_left]]
	name = "help"
	name_color = 16645526
	value_color = 5636095
	enabled_color = 5635925
	disabled_color = 16733525
	enabled = true

	[modules_left.lines]
		pie_graph = false
		fps_tps = false
		help = true

