chunks = false
base = true
quests = true
teams = false
essentials = true
ultimine = true
backups = false
polyLib = false

[versions]
chunksVersion = "5257897"
baseVersion = "5051953"
questsVersion = "5192381"
teamsVersion = "5176343"
essentialsVersion = "4896152"
ultimineVersion = "5005006"
backupsVersion = "4834403"
polyLibVersion = "5218944"
